name: 'Dockerfile linter'
description: 'Lint dockerfile issues via hadolint'

inputs:
  dockerfile:
    description: "Where is placed dockerfile"
    required: false
    default: Dockerfile
  recursive:
    description: "Search for Dockerfiles in the nested folders"
    required: false
    default: true

runs:
  using: "composite"
  steps:

  - uses: hadolint/hadolint-action@v2.0.0
    with:
      dockerfile: ${{ inputs.dockerfile }}
      recursive: ${{ inputs.recursive }}