rules:
  - id: detected-generic-secrets
    patterns:
      - pattern-regex: (([aA][pP][iI](_)?[kK][eE][yY])|([sS][eE][cC][rR][eE][tT])|([pP][aA][sS][sS][wW][oO][rR][dD]))(\s+)?[:=](\s+)?['|\"](?!\s*$).+?['|\"]
      - pattern-not-regex: (['|\"](\$)?\{\{.*?\}\}['|\"])
      - pattern-not-regex: os.getenv
      - pattern-not-regex: (=(\s+)?['|"]\$)
    languages:
      - regex
    message: Generic secrets detected. This is a sensitive credential and
      should not be hardcoded here.
    severity: ERROR
    metadata:
      category: security
      technology:
        - secrets
      confidence: HIGH
      license: Commons Clause License Condition v1.0[LGPL-2.1-only]
