rules:
  - id: detected-password-in-url
    patterns:
      - pattern-regex: ([a-zA-Z]{3,10}://[^/\\s:@]{3,20}:[^/\\s:@]{3,20}@.{1,100}[\"'\\s])
    languages:
      - regex
    message: Password in url detected. This is a sensitive credential and
      should not be hardcoded here.
    severity: ERROR
    metadata:
      category: security
      technology:
        - secrets
      confidence: HIGH
      license: Commons Clause License Condition v1.0[LGPL-2.1-only]
