rules:
  - id: detected-slack-access-token
    patterns:
      - pattern-regex: (xox[pborsa]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})
    languages:
      - regex
    message: Slack access token detected. This is a sensitive credential and
      should not be hardcoded here.
    severity: ERROR
    metadata:
      category: security
      technology:
        - secrets
      confidence: HIGH
      license: Commons Clause License Condition v1.0[LGPL-2.1-only]
