name: 'Security linter'
description: 'Lint security issues via semgrep'
inputs:
  languages:
    required: false
    description: The languages to be analysed
  skip-codeql:
    required: false
    default: 'false'
    description: Skip codeql if repo has not contain any supported languages
runs:
  using: "composite"
  steps:

    - name: TruffleHog OSS
      uses: lidofinance/linters/.github/actions/lint-security/trufflehog@master
      if: always()
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD

    - name: Copy semgrep rules to .semgrep
      if: always()
      run: cp -r ${{ github.action_path }}/rules ${{ github.workspace }}/.semgrep
      shell: bash

    - name: Run semgrep security checks
      uses: semgrep/semgrep-action@v1
      if: always()
      with:
        config: >-
          .semgrep

    - name: Initialize CodeQL
      uses: github/codeql-action/init@ee117c905ab18f32fa0f66c2fe40ecc8013f3e04 # v3.28.4
      if: ${{ always() && !github.event.repository.private && inputs.skip-codeql == 'false' }}
      with:
        languages: ${{ inputs.languages }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@ee117c905ab18f32fa0f66c2fe40ecc8013f3e04 # v3.28.4
      if: ${{ always() && !github.event.repository.private && inputs.skip-codeql == 'false' }}
