name: Lint Actions

on:
  workflow_call:

jobs:
  actions-linter:
    name: Check GitHub Actions issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: lidofinance/linters/.github/actions/lint-actions@actionlint-from-docker
