name: Lint Python

on:
  workflow_call:
    inputs:
      dirs:
        required: true
        type: string
        default: "./"
      pylint-args:
        required: false
        type: string
        default: ""
      requirements-file:
        required: false
        type: string
        default: "requirements.txt"
      python-version:
        required: false
        type: string
        default: "3.10.*"
jobs:
  python-linters:
    name: Check python code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ inputs.python-version }}

      - name: Check package manager
        id: package_manager
        run: > 
          test -f ./poetry.lock && 
          echo '::set-output name=value::poetry' || 
          echo '::set-output name=value::pip'

      - name: Install requirements from ${{ inputs.requirements-file }}
        if: ${{ steps.package_manager.outputs.value == 'pip' }}
        run: pip install -r ${{ inputs.requirements-file }}

      - name: Install poetry requirements
        if: ${{ steps.package_manager.outputs.value == 'poetry' }}
        run: >
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - &&
          source $HOME/.poetry/env &&
          poetry install

      - uses: lidofinance/linters/.github/actions/lint-python@master
        with:
          dirs: ${{ inputs.dirs }}
          pylint-args: ${{ inputs.pylint-args }}
