name: Lint Security

on:
  workflow_call:
    inputs:
      languages:
        required: false
        type: string
      skip-codeql:
        required: false
        default: false
        type: boolean
        description: Skip codeql if repo has not contain any supported languages

jobs:
  security-linters:
    name: Check security issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: ./.github/actions/lint-security
        with:
          languages: ${{ inputs.languages }}
          skip-codeql: ${{ inputs.skip-codeql }}
